TurnosWeb/Models/Turno.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TurnosWeb.Models.Enum;
using TurnosWeb.Models.MetaData;

namespace TurnosWeb.Models
{
    [Table("Turno")]
    [MetadataType(typeof(ITurno))]
    public class Turno:EntidadBase,ITurno
    {
        // Ids
        public Guid MedicoId { get; set; }
        public Guid PacienteId { get; set; }

        // Propiedades Core
        public DateTime Fecha { get; set; }
        public TimeSpan HoraTurno { get; set; }
        public int NumeroTurno { get; set; }
        public bool EstaBorrado { get; set; }

        // Enums
        public EstadoTurno EstadoTurno { get; set; }

        // Propiedades de Navegacion
        [ForeignKey("MedicoId")]
        public virtual Medico Medico { get; set; }
        [ForeignKey("PacienteId")]
        public virtual Paciente Paciente { get; set; }
    }
}

TurnosWeb/Controllers/TurnosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurnosWeb.Models;
using TurnosWeb.Models.Enum;
using Microsoft.AspNet.Identity;
using TurnosWeb.Models.ViewModels;
using Newtonsoft.Json;

namespace TurnosWeb.Controllers
{
    public class TurnosController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        TurnosWeb.Servicios.TurnoServicio turnoServicio = new Servicios.TurnoServicio();
        // GET: Turnos
        [Authorize(Roles = "Paciente")]
        public ActionResult Index()
        { 
            ViewBag.Medicos = db.Medicos.ToList();

            return View();
        }
         


        private bool VarificarSiExisteTurno(TurnoViewModel turno)
        {
            var idMedico = db.Medicos.Where(w => w.Email == turno.Email).FirstOrDefault().Id;
            var horario = new ApplicationDbContext();
            //var horarioDisponible = horario.Horarios.Where(x => x.Dia == (DiaDeLaSemana)turno.Fecha.DayOfWeek && x.MedicoId == idMedico && x.HoraFin <= turno.HoraTurno && x.HoraInicio >= turno.HoraTurno).ToList();
            //if (horarioDisponible.Count() > 0)
            //{
            //    var turnoDisponible = horario.Turnos.Where(x => x.MedicoId == idMedico && x.Fecha == turno.Fecha && x.HoraTurno == turno.HoraTurno).ToList();
            //    if (turnoDisponible.Count() > 0)
            //    {
            //        return false;
            //    }
            //}
            return true;
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TurnosDisponibles(Turno turno,string Medicos)
        {
            if (db.Horarios.Any(x=>x.MedicoId==turno.MedicoId))
            { 
                return View(turnoServicio.ObtenerTurnos(turno.MedicoId, turno.Fecha).ToList());

            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        public ActionResult Reservar(TurnoVM turno)
        {
            var usuarioID= User.Identity.GetUserId();
            var id = db.Pacientes.Where(x => x.UsuarioId == usuarioID).FirstOrDefault().Id;
            turno.PacienteId = id;
            turnoServicio.AgregarTurno(turno);
            return RedirectToAction("Index", "Home");
        }
        public ActionResult ReservaTurno()
        {
            var esp = db.Especialidades.ToList();
            return View(esp);
        }
        [HttpPost]
        public ActionResult GetProfecional(string json)
        { 

            SelectViewModel  selecthtml = JsonConvert.DeserializeObject<SelectViewModel>(json);
            var profecionales = (from p in db.Medicos.Where(w => w.Especialidad.Descripcion == selecthtml.Descripcion) select new { id = p.Id, descripcion = p.Apellido }).ToList();
            return Json(profecionales, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Getturnos(Turno turnos, string Medicos)
        {

            Servicios.TurnoServicio ts = new Servicios.TurnoServicio();
            //var turnosts.ObtenerTurnos(turnos.MedicoId, turnos.Fecha).ToList();

            //ts.ObtenerTurnos(medico, DateTime.Now);
            return Json(new
            {
                TurnoId = new Guid(),
                NumeroTurno = 1,
                EstadoTurno = EstadoTurno.Disponible.ToString(),
                HoraTurno = new TimeSpan(12, 0, 0).Hours.ToString()
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

TurnosWeb/Views/Turnos/Index.cshtml
@model TurnosWeb.Models.Turno

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("TurnosDisponibles", "Turnos")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Turno</h4>
        <hr />
   



        <div class="form-group">
            @Html.LabelFor(model => model.MedicoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MedicoId", new SelectList( ViewBag.Medicos,"Id", "Nombre"),"--",new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>
        

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>
 

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Continuar" class="form-control" />            
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TurnosWeb/Views/Turnos/TurnosDisponibles.cshtml
@model IEnumerable<TurnosWeb.Models.Turno>

@{
    ViewBag.Title = "TurnosDisponibles";
}

<h2>TurnosDisponibles</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Medico.UsuarioId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Paciente.UsuarioId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoraTurno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstaBorrado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstadoTurno)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Medico.UsuarioId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Paciente.UsuarioId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HoraTurno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EstaBorrado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EstadoTurno)
        </td>
        <td>
            @Html.ActionLink("Reservar", "Reservar", item) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>